meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: monitor_server_z1
    template: monitor-server
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties: {}

networks: (( merge ))

properties: {}
